version: '3'
services:
  mongodb:
    container_name: mongoStreamloots
    image: mongo:3.6
    restart: always
    ports:
      - '27017:27017'
    # Environment variable file
    env_file: .env
    # Env variables
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
      - MONGO_DB=${MONGO_DB}
    # Create volume for creating users for mongo dbs
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
